### PR TITLE
Upgrade pyo3 to 0.12

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
Can't get the alpine Dockerfile work, errored with:

```
💥 maturin failed
  Caused by: Failed to ensure manylinux compliance
  Caused by: Your library is not manylinux compliant because it links the following forbidden libraries: ["libc.musl-x86_64.so.1"]
```

**Comment by messense** [comment]
Fixed alpine Docker build.

**Comment by bobleujr** [comment]
Will this be merged eventually?

**Comment by SharpEdgeMarshall** [comment]
@bobleujr Probably we'll go back to pure python in the future so I don't think we will merge this.

**Comment by SharpEdgeMarshall** [comment]
Rebased and merged by #43

**Comment by simobasso** [comment]
Thanks, @messense! We introduced your commits in #43; sorry for the lag 😅

**Pull request closed without merging**
