### PR TITLE
Build & deploy manylinux binary distributions

### LINKED ISSUE #8: Build binary wheels
I'd love to be able to install this without having a rust compiler. Have you thought of building binary manylinux wheels and pushing them to PyPI?

### LINKED ISSUE #13: error: Can not find Rust compiler
When I try to install the packet, it shows the following error:
Is there pre-build wheel available?
> pip install celery-exporter
Collecting celery-exporter
  Using cached https://files.pythonhosted.org/packages/a2/25/497d1aad19bde44ef918cf71be1dc23799126888d40af58e7b5a0e65542e/celery-exporter-1.4.0.tar.gz
Collecting click>=7celery>=4 (from celery-exporter)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
     |████████████████████████████████| 81kB 174kB/s
Collecting prometheus_client>=0.0.20 (from celery-exporter)
  Downloading https://files.pythonhosted.org/packages/b3/23/41a5a24b502d35a4ad50a5bb7202a5e1d9a0364d0c12f56db3dbf7aca76d/prometheus_client-0.7.1.tar.gz
Building wheels for collected packages: celery-exporter, prometheus-client
  Building wheel for celery-exporter (setup.py) ... error
  ERROR: Complete output from command /project/capspae/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ioypwnlq/celery-exporter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dxsngnta --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/celery_exporter
  copying celery_exporter/monitor.py -> build/lib/celery_exporter
  copying celery_exporter/core.py -> build/lib/celery_exporter
  copying celery_exporter/metrics.py -> build/lib/celery_exporter
  copying celery_exporter/__main__.py -> build/lib/celery_exporter
  copying celery_exporter/utils.py -> build/lib/celery_exporter
  copying celery_exporter/__init__.py -> build/lib/celery_exporter
  running build_ext
  running build_rust
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for celery-exporter

### PR DESCRIPTION
**Pull request by MRoci**
fix #8
fix #13

### CODE REVIEW

**Comment by SharpEdgeMarshall** [comment]
@MRoci did you try the new wheel building code?

**Comment by MRoci** [comment]
The only untested is the semantic for docker on travis

**Comment by SharpEdgeMarshall** [comment]
Good to merge?

**Comment by MRoci** [comment]
yup

**Comment by LowLevel96** [comment]
Can this be merged please?

**Pull request merged**
